# docker-sync.yml
version: "2"
syncs:
# this name has to be unique and is used in docker-compose.yml as well
  easybreeding-data-sync:
    src: '../' # the directory on the host system
    sync_host_ip: '127.0.0.1' # localhost for docker for mac
    sync_host_port: 10872 # unique port
#    sync_strategy: 'native_osx'
    sync_strategy: 'unison'
